name: FunctionApp
summary: This is a deployment of an Azure Function App using Bicep with managed identity authentication.
description: Deploys a secure Function App with App Service Plan, Storage Account, and Application Insights. Uses managed identity for storage authentication, disables basic publishing credentials, and follows Azure security best practices.
templatePath: main.bicep
parameters:
- id: "appName"
  name: "Function App Name"
  description: "The name of the function app that you wish to create"
  type: "string"
  default: ""
- id: "runtime"
  name: "Runtime Stack"
  description: "The language worker runtime to load in the function app"
  type: "string"
  default: "dotnet"
  allowed:
    - "node"
    - "dotnet"
    - "java"
    - "python"
- id: "runtimeVersion"
  name: "Runtime Version"
  description: "The version of the runtime to use"
  type: "string"
  default: "8"
- id: "sku"
  name: "Pricing Tier"
  description: "The pricing tier for the hosting plan"
  type: "string"
  default: "Y1"
  allowed:
    - "Y1"
    - "EP1"
    - "EP2"
    - "EP3"
- id: "location"
  name: "Location"
  description: "Location to deploy the environment resources. If not specified, will deploy to the region of the project"
  type: "string"
  default: ""
runner: Bicep